bus:
  width: 4 # bytes
  clk_cycle: 5.0 # ns
  arbitration_delay: 5.0 # ns

ram:
  size: 16 # KB
  width: 1 # bytes
  clk_cycle: 3.0 # ns
  access_delay: 20.0 # ns

interconnect_protocol:
  width: 4 # bytes
  flit_size: 64 # bytes
  buffer_size: 256 # bytes
  clk_cycle: 5.0 # ns

interconnect:
  width: 1 # bytes
  buffer_size: 128 # bytes
  clk_cycle: 5.0 # ns