cores:
  num: 1
  clk_cycle: 1 # ns, GEM5
  irq_hw_delay: 2 # ns
  irq_sw_delay: 100 # cycles
memory:
  size: 512 # KB
  clk_cycle: 3 # ns, GEM5
  access_latency: 1 # cycles, GEM5
dma_engine:
  clk_cycle: 5 # ns
extensions:
  clk_cycle: 5 # ns
axi:
  width: 32 # bits, GEM5
  clk_cycle: 5 # ns