cores:
  num: 1
  clk_cycle: 1 # ns
  irq_delay: 2 # ns
memory:
  size: 512 # KB
  clk_cycle: 3 # ns
  access_latency: 1 # cycles
dma_engine:
  clk_cycle: 5 # ns
extensions:
  clk_cycle: 5 # ns
axi:
  width: 32 # bits
  clk_cycle: 5 # ns