single-core:
  system:
    clk_cycle: 5 # ns
  cores:
    num: 1
    clk_cycle: 1 # ns
    irq_delay: 2 # ns
  cache:
    size: 256 # bytes
    block_size: 32 # bytes
    store_buffer_size: 4 # entries
  ram:
    size: 512 # KB
    clk_cycle: 3 # ns
  axi:
    width: 32 # bits

dual-core:
  system:
    clk_cycle: 5 # ns
  cores:
    num: 2
    clk_cycle: 1 # ns
    irq_delay: 2 # ns
  cache:
    size: 256 # bytes
    block_size: 32 # bytes
    store_buffer_size: 4 # entries
  ram:
    size: 512 # KB
    clk_cycle: 3 # ns
  axi:
    width: 32 # bits

quad-core:
  system:
    clk_cycle: 5 # ns
  cores:
    num: 4
    clk_cycle: 1 # ns
    irq_delay: 2 # ns
  cache:
    size: 256 # bytes
    block_size: 32 # bytes
    store_buffer_size: 4 # entries
  ram:
    size: 512 # KB
    clk_cycle: 3 # ns
  axi:
    width: 32 # bits

memory:
  system:
    clk_cycle: 5 # ns
  cores:
    num: 0
  ram:
    size: 512 # KB
    clk_cycle: 3 # ns
  axi:
    width: 32 # bits