single-core:
  cores:
    num: 1
    clk_cycle: 1 # ns
    irq_lines: 2
    irq_delay: 2 # ns
  cache:
    size: 256 # bytes
    block_size: 32 # bytes
    store_buffer_size: 4 # entries
    clk_cycle: 1 # ns
  ram:
    size: 512 # KB
    clk_cycle: 3 # ns
  axi:
    width: 32 # bits
    clk_cycle: 5 # ns

dual-core:
  cores:
    num: 2
    clk_cycle: 1 # ns
    irq_lines: 2
    irq_delay: 2 # ns
  cache:
    size: 256 # bytes
    block_size: 32 # bytes
    store_buffer_size: 4 # entries
    clk_cycle: 1 # ns
  ram:
    size: 512 # KB
    clk_cycle: 3 # ns
  axi:
    width: 32 # bits
    clk_cycle: 5 # ns

quad-core:
  cores:
    num: 4
    clk_cycle: 1 # ns
    irq_lines: 2
    irq_delay: 2 # ns
  cache:
    size: 256 # bytes
    block_size: 32 # bytes
    store_buffer_size: 4 # entries
    clk_cycle: 1 # ns
  ram:
    size: 512 # KB
    clk_cycle: 3 # ns
  axi:
    width: 32 # bits
    clk_cycle: 5 # ns

memory:
  cores:
    num: 0
  ram:
    size: 512 # KB
    clk_cycle: 3 # ns
  axi:
    width: 32 # bits
    clk_cycle: 5 # ns