cores:
  clk_cycle: 1 # ns
  irq_delay: 2 # ns

cache:
  size: 512 # bytes
  block_size: 32 # bytes
  store_buffer_size: 8 # entries

axi:
  width: 32 # bits
  clk_cycle: 5 # ns

ram:
  size: 512 # KB
  clk_cycle: 3 # ns