interconnect_protocol:
  flit_size: 64 # bytes
  overhead_size: 0 # bytes
  
interconnect:
  staging_buffer_size: 1024 # bytes
  link_buffer_size: 512 # bytes
  bandwidth_chiplets: 10.0 # GB/s
  bandwidth_fpga: 5.0 # GB/s
  efficiency: 2.0 # pJ/bit