# PCIe 6.0 x16
interconnect_protocol:
  # https://pcisig.com/blog/evolution-pci-express-specification-its-sixth-generation-third-decade-and-still-going-strong
  flit_size: 256 # bytes
  overhead_size: 20 # bytes
  fec_delay: 3.0 # ns
  
interconnect:
  staging_buffer_size: 1024 # bytes
  link_buffer_size: 512 # bytes
  # https://pcisig.com/pci-express-6.0-specification
  bandwidth: 128.0 # GB/s
  # https://pcisig.com/pcie%C2%AE-60-specification-webinar-qa-leveling-l0p
  efficiency: 5.0 # pJ/bit