# PCIe 6.0 x16
# https://pcisig.com/blog/evolution-pci-express-specification-its-sixth-generation-third-decade-and-still-going-strong
interconnect_protocol:
  flit_size: 256 # bytes
  header_size: 20 # bytes
  pre_delay: 5.0 # ns
  post_delay: 5.0 # ns
  fec_delay: 3.0 # ns
  irq_delay: 2.0 # ns
  
interconnect:
  buffer_size: 512 # bytes
  bandwidth_chiplets: 128.0 # GB/s
  bandwidth_fpga: 128.0 # GB/s