interconnect_protocol:
  buffer_size: 512 # bytes
  flit_size: 1 # bytes
  header_size: 0 # bytes
  pre_delay: 0.5 # ns
  post_delay: 0.1 # ns
  irq_delay: 2.0 # ns
  
interconnect:
  buffer_size: 512 # bytes
  bandwidth: 0.05 # Gb/s