interconnect_protocol:
  flit_size: 1 # bytes
  overhead_size: 0 # bytes
  
interconnect:
  staging_buffer_size: 1024 # bytes
  link_buffer_size: 512 # bytes
  bandwidth: 0.00625 # GB/s
  efficiency: 10.0 # pJ/bit