use_dma: false
protocol:
  clk_cycle: 1 # ns
  staging_buffer_size: 1024 # bytes
  flit_size: 68 # bytes
  overhead_size: 4 # bytes
  retries: 4
  
phy:
  clk_cycle: 1 # ns
  link_buffer_size: 512 # bytes
  bandwidth: 128.0 # GB/s
  efficiency: 1.0 # pJ/bit